FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED=1

RUN pip install pipenv
RUN pipenv --python 3.11

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /code
COPY ./api /code
RUN apt update && \
	apt install libpq-dev python3-dev g++ unixodbc-dev gnupg2 -y && \
    pipenv install --system --deploy

EXPOSE 8000

ENTRYPOINT ["bash", "./entrypoint.sh"]
