FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED=1

RUN pip install pipenv

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /code
COPY ./api /code

RUN apt update && \
	apt install libpq-dev python3-dev g++ unixodbc-dev gnupg2 -y && \
    pipenv install --system --deploy

ENTRYPOINT ["celery", "-A", "django_template", "worker", "--concurrency=4", "-n", "celery@%d", "-s", "Django", "-l", "INFO", "-E", "-B", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
