FROM python:3.10-slim-bullseye

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libpq-dev python3-dev g++ unixodbc-dev gnupg2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY . /code/

COPY ./api/requirements.txt /code/
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["celery", "-A", "django_template", "worker", "--concurrency=4", "-n", "celery@%h", "-l", "INFO"]
